In [8]:
import numpy as np
X = np.array([[1, 1], [2, 1], [3, 1.2], [4, 1], [5, 0.8], [6, 1]])
from sklearn.decomposition import NMF
model = NMF(n_components=3, init='random', random_state=0)
W = model.fit_transform(X)
H = model.components_

In [9]:
X

array([[1. , 1. ],
       [2. , 1. ],
       [3. , 1.2],
       [4. , 1. ],
       [5. , 0.8],
       [6. , 1. ]])

In [10]:
#column vectors of X can be written as linear combination of W
#columns of W can be regarded as basis for approximating X
W

array([[0.38534454, 0.4675586 , 0.00799441],
       [0.        , 0.34002261, 0.94060871],
       [1.34627306, 0.49279364, 0.21257051],
       [1.49619407, 0.31673295, 0.68516976],
       [0.26846283, 0.        , 2.44645467],
       [2.44632733, 0.2376055 , 0.94057293]])

In [11]:
H

array([[1.66585801, 0.08635763],
       [0.73400202, 2.06222242],
       [1.86096512, 0.31755657]])